# Copyright (c) Ondrej Balaz

# Stay within free quota (F1 has 28h free limit; 1 replica will then never go
# over limit even when running 24h).
# NOTE This holds only if no other things are running in GAE.
instance_class: F1
automatic_scaling:
  max_instances: 1

runtime: go114
main: github.com/blami/blami.github.io/api/cmd/apisvc

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

includes:
  - secrets.yaml
